select * from information_schema.columns 
where table_schema='public' and data_type ilike '%time%'
order by data_type;

select distinct table_name from information_schema.columns 
where table_schema='public' and data_type ilike '%timestamp without time zone%'
order by 1;

--Data Type Changes
alter table exitwithoutsavetest alter column createddate type timestamp with time zone;
alter table gradeband alter column createdate type timestamp with time zone;
alter table gradeband alter column modifieddate type timestamp with time zone;
alter table groupauthoritiesexclusion alter column createddate type timestamp with time zone;
alter table groupauthoritiesexclusion alter column modifieddate type timestamp with time zone;
alter table itimclog alter column createddate type timestamp with time zone;
alter table ititestsessionhistory alter column confirmdate type timestamp with time zone;
alter table ititestsessionhistory alter column createddate type timestamp with time zone;
alter table ititestsessionhistory alter column modifieddate type timestamp with time zone;
alter table ititestsessionhistory alter column saveddate type timestamp with time zone;
alter table lcsstudentstests alter column createddate type timestamp with time zone;
alter table lcsstudentstests alter column modifieddate type timestamp with time zone;
alter table modulereport alter column createddate type timestamp with time zone;
alter table modulereport alter column modifieddate type timestamp with time zone;
alter table profileitemattributenameattributecontainer alter column createddate type timestamp with time zone;
alter table profileitemattributenameattributecontainer alter column modifieddate type timestamp with time zone;
alter table profileitemattrnameattrcontainerviewoptions alter column createddate type timestamp with time zone;
alter table profileitemattrnameattrcontainerviewoptions alter column modifieddate type timestamp with time zone;
alter table stimulusdescriptionview alter column createdate type timestamp with time zone;
alter table stimulusdescriptionview alter column modifieddate type timestamp with time zone;
alter table studentadaptivetest alter column createddate type timestamp with time zone;
alter table studentadaptivetest alter column modifieddate type timestamp with time zone;
alter table studentadaptivetestfinaltheta alter column createddate type timestamp with time zone;
alter table studentadaptivetestfinaltheta alter column modifieddate type timestamp with time zone;
alter table studentadaptivetestthetastatus alter column createddate type timestamp with time zone;
alter table studentadaptivetestthetastatus alter column modifieddate type timestamp with time zone;
alter table studentassessmentprogram alter column createddate type timestamp with time zone;
alter table studentassessmentprogram alter column modifieddate type timestamp with time zone;
alter table studentaudit alter column createdate type timestamp with time zone;
alter table studentaudit alter column modifieddate type timestamp with time zone;
alter table studentnodeprobability alter column createddate type timestamp with time zone;
alter table studentresponsescore alter column createdate type timestamp with time zone;
alter table studentresponsescore alter column modifieddate type timestamp with time zone;
alter table studentsadaptivetestsections alter column createddate type timestamp with time zone;
alter table studentsadaptivetestsections alter column modifieddate type timestamp with time zone;
alter table studentsresponseparameters alter column createddate type timestamp with time zone;
alter table studentsresponseparameters alter column modifieddate type timestamp with time zone;
alter table studentsresponses alter column createddate type timestamp with time zone;
alter table studentsresponses alter column modifieddate type timestamp with time zone;
alter table studentsresponsescopy alter column createddate type timestamp with time zone;
alter table studentsresponsescopy alter column deletedtime type timestamp with time zone;
alter table studentsresponsescopy alter column modifieddate type timestamp with time zone;
alter table studentstests alter column createddate type timestamp with time zone;
alter table studentstests alter column enddatetime type timestamp with time zone;
alter table studentstests alter column modifieddate type timestamp with time zone;
alter table studentstests alter column startdatetime type timestamp with time zone;
alter table studentstestsections alter column createddate type timestamp with time zone;
alter table studentstestsections alter column enddatetime type timestamp with time zone;
alter table studentstestsections alter column lastactive type timestamp with time zone;
alter table studentstestsections alter column modifieddate type timestamp with time zone;
alter table studentstestsections alter column startdatetime type timestamp with time zone;
alter table studentstestsectionstasks alter column createdate type timestamp with time zone;
alter table studentstestsectionstasks alter column modifieddate type timestamp with time zone;
alter table studentstestsectionstasksfoils alter column createdate type timestamp with time zone;
alter table studentstestsectionstasksfoils alter column modifieddate type timestamp with time zone;
alter table tasklayout alter column createdate type timestamp with time zone;
alter table tasklayout alter column modifieddate type timestamp with time zone;
alter table taskvariantrescore alter column processeddate type timestamp with time zone;
alter table testsectionstaskvariants alter column createddate type timestamp with time zone;
alter table testsectionstaskvariants alter column modifieddate type timestamp with time zone;
alter table textaccommodation alter column createdate type timestamp with time zone;
alter table textaccommodation alter column modifieddate type timestamp with time zone;
alter table userorganizationsgroups alter column activationnoexpirationdate type timestamp with time zone;
alter table userpasswordreset alter column password_expiration_date type timestamp with time zone;
alter table usersecurityagreement alter column agreementsigneddate type timestamp with time zone;
alter table usertest alter column createddate type timestamp with time zone;
alter table usertest alter column enddatetime type timestamp with time zone;
alter table usertest alter column modifieddate type timestamp with time zone;
alter table usertest alter column startdatetime type timestamp with time zone;
alter table usertestresponse alter column createddate type timestamp with time zone;
alter table usertestresponse alter column modifieddate type timestamp with time zone;
alter table usertestsection alter column createddate type timestamp with time zone;
alter table usertestsection alter column enddatetime type timestamp with time zone;
alter table usertestsection alter column modifieddate type timestamp with time zone;
alter table usertestsection alter column startdatetime type timestamp with time zone;
alter table usertestsectiontask alter column createddate type timestamp with time zone;
alter table usertestsectiontask alter column modifieddate type timestamp with time zone;
alter table usertestsectiontaskfoil alter column createddate type timestamp with time zone;
alter table usertestsectiontaskfoil alter column modifieddate type timestamp with time zone;
---------------------------------------------------------------------------------------
--Data Default Changes
alter table aartuser alter column createddate set default ('now'::text)::timestamp with time zone;
alter table aartuser alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table archivetablecount alter column createddate set default ('now'::text)::timestamp with time zone;
alter table archivetablecount alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table assessment alter column createdate set default ('now'::text)::timestamp with time zone;
alter table assessment alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table assessmentprogram alter column createdate set default ('now'::text)::timestamp with time zone;
alter table assessmentprogram alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table assessmentstestcollections alter column createddate set default ('now'::text)::timestamp with time zone;
alter table assessmentstestcollections alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table authorities alter column createddate set default ('now'::text)::timestamp with time zone;
alter table authorities alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table blueprint alter column createddate set default ('now'::text)::timestamp with time zone;
alter table blueprint alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table category alter column createddate set default ('now'::text)::timestamp with time zone;
alter table category alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table categorytype alter column createddate set default ('now'::text)::timestamp with time zone;
alter table categorytype alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table ccqscore alter column createddate set default ('now'::text)::timestamp with time zone;
alter table ccqscore alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table ccqscoreitem alter column createddate set default ('now'::text)::timestamp with time zone;
alter table ccqscoreitem alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table cognitivetaxonomy alter column createdate set default ('now'::text)::timestamp with time zone;
alter table cognitivetaxonomy alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table cognitivetaxonomydimension alter column createdate set default ('now'::text)::timestamp with time zone;
alter table cognitivetaxonomydimension alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table contentarea alter column createdate set default ('now'::text)::timestamp with time zone;
alter table contentarea alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table contentframework alter column createdate set default ('now'::text)::timestamp with time zone;
alter table contentframework alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table contentframeworkdetail alter column createdate set default ('now'::text)::timestamp with time zone;
alter table contentframeworkdetail alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table domainaudithistory alter column createddate set default ('now'::text)::timestamp with time zone;
alter table enrollment alter column createddate set default ('now'::text)::timestamp with time zone;
alter table enrollment alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table enrollmentsrosters alter column createddate set default ('now'::text)::timestamp with time zone;
alter table enrollmentsrosters alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table externalstudentreports alter column createddate set default ('now'::text)::timestamp with time zone;
alter table externalstudentreports alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table fieldspecification alter column createddate set default ('now'::text)::timestamp with time zone;
alter table fieldspecification alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table fieldspecificationsrecordtypes alter column createddate set default ('now'::text)::timestamp with time zone;
alter table fieldspecificationsrecordtypes alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table firstcontactsurveysettings alter column createddate set default ('now'::text)::timestamp with time zone;
alter table firstcontactsurveysettings alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table foil alter column createdate set default ('now'::text)::timestamp with time zone;
alter table foil alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table frameworklevel alter column createdate set default ('now'::text)::timestamp with time zone;
alter table frameworklevel alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table frameworktype alter column createdate set default ('now'::text)::timestamp with time zone;
alter table frameworktype alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table gradeband alter column createdate set default ('now'::text)::timestamp with time zone;
alter table gradeband alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table gradecourse alter column createdate set default ('now'::text)::timestamp with time zone;
alter table gradecourse alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table groupauthorities alter column createddate set default ('now'::text)::timestamp with time zone;
alter table groupauthorities alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table groupauthoritiesexclusion alter column createddate set default ('now'::text)::timestamp with time zone;
alter table groupauthoritiesexclusion alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table grouprestrictions alter column createddate set default ('now'::text)::timestamp with time zone;
alter table grouprestrictions alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table groups alter column createddate set default ('now'::text)::timestamp with time zone;
alter table groups alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table interfacerequesthistory alter column requesteddate set default ('now'::text)::timestamp with time zone;
alter table itimclog alter column createddate set default ('now'::text)::timestamp with time zone;
alter table lcsstudentstests alter column createddate set default ('now'::text)::timestamp with time zone;
alter table lcsstudentstests alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table modulereport alter column createddate set default ('now'::text)::timestamp with time zone;
alter table modulereport alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table operationaltestwindow alter column createddate set default ('now'::text)::timestamp with time zone;
alter table operationaltestwindowsessionrule alter column createddate set default ('now'::text)::timestamp with time zone;
alter table operationaltestwindowsessionrule alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table operationaltestwindowstudent alter column createddate set default ('now'::text)::timestamp with time zone;
alter table operationaltestwindowstudent alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table organization alter column createddate set default ('now'::text)::timestamp with time zone;
alter table organization alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table organizationannualresets alter column createddate set default ('now'::text)::timestamp with time zone;
alter table organizationannualresets alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table organizationrelation alter column createddate set default ('now'::text)::timestamp with time zone;
alter table organizationrelation alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table organizationtype alter column createddate set default ('now'::text)::timestamp with time zone;
alter table organizationtype alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table orgassessmentprogram alter column createddate set default ('now'::text)::timestamp with time zone;
alter table orgassessmentprogram alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table policy alter column createddate set default ('now'::text)::timestamp with time zone;
alter table policy alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table profileitemattribute alter column createddate set default ('now'::text)::timestamp with time zone;
alter table profileitemattribute alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table profileitemattributecontainer alter column createddate set default ('now'::text)::timestamp with time zone;
alter table profileitemattributecontainer alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table profileitemattributenameattributecontainer alter column createddate set default ('now'::text)::timestamp with time zone;
alter table profileitemattributenameattributecontainer alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table profileitemattrnameattrcontainerviewoptions alter column createddate set default ('now'::text)::timestamp with time zone;
alter table profileitemattrnameattrcontainerviewoptions alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table proportionmetrics alter column createddate set default ('now'::text)::timestamp with time zone;
alter table proportionmetrics alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table rawscoresectionweights alter column createddate set default ('now'::text)::timestamp with time zone;
alter table rawscoresectionweights alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table reportassessmentprogram alter column createdate set default ('now'::text)::timestamp with time zone;
alter table reportassessmentprogram alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table restriction alter column createddate set default ('now'::text)::timestamp with time zone;
alter table restriction alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table restrictionsauthorities alter column createddate set default ('now'::text)::timestamp with time zone;
alter table restrictionsauthorities alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table restrictionsorganizations alter column createddate set default ('now'::text)::timestamp with time zone;
alter table restrictionsorganizations alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table roster alter column createddate set default ('now'::text)::timestamp with time zone;
alter table roster alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table rubricscore alter column date set default ('now'::text)::timestamp with time zone;
alter table scoringassignment alter column createddate set default ('now'::text)::timestamp with time zone;
alter table scoringassignmentscorer alter column createddate set default ('now'::text)::timestamp with time zone;
alter table scoringassignmentstudent alter column createddate set default ('now'::text)::timestamp with time zone;
alter table specialcircumstance alter column createdate set default ('now'::text)::timestamp with time zone;
alter table specialcircumstance alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table statespecialcircumstance alter column createdate set default ('now'::text)::timestamp with time zone;
alter table statespecialcircumstance alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table stimulusvariant alter column createdate set default ('now'::text)::timestamp with time zone;
alter table stimulusvariant alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table stimulusvariantattachment alter column createdate set default ('now'::text)::timestamp with time zone;
alter table stimulusvariantattachment alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table studentadaptivetestfinaltheta alter column createddate set default ('now'::text)::timestamp with time zone;
alter table studentadaptivetestfinaltheta alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table studentadaptivetestthetastatus alter column createddate set default ('now'::text)::timestamp with time zone;
alter table studentadaptivetestthetastatus alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table studentassessmentprogram alter column createddate set default ('now'::text)::timestamp with time zone;
alter table studentassessmentprogram alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table studentbandrecommendation alter column createdate set default ('now'::text)::timestamp with time zone;
alter table studentbandrecommendation alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table studentnodeprobability alter column createddate set default ('now'::text)::timestamp with time zone;
alter table studentprofileitemattributevalue alter column createddate set default ('now'::text)::timestamp with time zone;
alter table studentprofileitemattributevalue alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table studentreportreprocess alter column createddate set default ('now'::text)::timestamp with time zone;
alter table studentreportreprocess alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table studentreporttestscores alter column createddate set default ('now'::text)::timestamp with time zone;
alter table studentsadaptivetestsections alter column createddate set default ('now'::text)::timestamp with time zone;
alter table studentsadaptivetestsections alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table studentsassessments alter column createddate set default ('now'::text)::timestamp with time zone;
alter table studentsassessments alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table studentspecialcircumstance alter column createdate set default ('now'::text)::timestamp with time zone;
alter table studentspecialcircumstance alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table studentsresponses_aart alter column createddate set default ('now'::text)::timestamp with time zone;
alter table studentsresponses_aart alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table studentstests alter column createddate set default ('now'::text)::timestamp with time zone;
alter table studentstests alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table studentstestsections_aart alter column createddate set default ('now'::text)::timestamp with time zone;
alter table studentstestsections_aart alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table studentstestshistory alter column acteddate set default ('now'::text)::timestamp with time zone;
alter table studentsurveyresponse alter column createddate set default ('now'::text)::timestamp with time zone;
alter table studentsurveyresponse alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table studenttracker alter column createddate set default ('now'::text)::timestamp with time zone;
alter table studenttracker alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table studenttrackerband alter column createddate set default ('now'::text)::timestamp with time zone;
alter table studenttrackerband alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table subscoresmissingstages alter column createddate set default ('now'::text)::timestamp with time zone;
alter table subscoresmissingstages alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table survey alter column createddate set default ('now'::text)::timestamp with time zone;
alter table survey alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table surveylabel alter column createddate set default ('now'::text)::timestamp with time zone;
alter table surveylabel alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table surveylabelprerequisite alter column createddate set default ('now'::text)::timestamp with time zone;
alter table surveylabelprerequisite alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table surveypagestatus alter column createddate set default ('now'::text)::timestamp with time zone;
alter table surveypagestatus alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table surveyresponse alter column createddate set default ('now'::text)::timestamp with time zone;
alter table surveyresponse alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table surveysection alter column createddate set default ('now'::text)::timestamp with time zone;
alter table surveysection alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table tasklayout alter column createdate set default ('now'::text)::timestamp with time zone;
alter table tasklayout alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table tasklayoutformat alter column createdate set default ('now'::text)::timestamp with time zone;
alter table tasklayoutformat alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table tasktype alter column createdate set default ('now'::text)::timestamp with time zone;
alter table tasktype alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table taskvariant alter column createdate set default ('now'::text)::timestamp with time zone;
alter table taskvariant alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table taskvariantrescore alter column createddate set default ('now'::text)::timestamp with time zone;
alter table taskvariantrescore alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table test alter column createdate set default ('now'::text)::timestamp with time zone;
alter table test alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table testcollection alter column createdate set default ('now'::text)::timestamp with time zone;
alter table testcollection alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table testingprogram alter column createdate set default ('now'::text)::timestamp with time zone;
alter table testingprogram alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table testlet alter column createdate set default ('now'::text)::timestamp with time zone;
alter table testlet alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table testsection alter column createdate set default ('now'::text)::timestamp with time zone;
alter table testsection alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table testsectionstaskvariants alter column createddate set default ('now'::text)::timestamp with time zone;
alter table testsectionstaskvariants alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table testsession alter column createddate set default ('now'::text)::timestamp with time zone;
alter table testsession alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table tool alter column createdate set default ('now'::text)::timestamp with time zone;
alter table tool alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table userassessmentprogram alter column createddate set default ('now'::text)::timestamp with time zone;
alter table userassessmentprogram alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table userfeedback alter column createddate set default ('now'::text)::timestamp with time zone;
alter table userfeedback alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table userorganizationsgroups alter column createddate set default ('now'::text)::timestamp with time zone;
alter table userorganizationsgroups alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table usersorganizations alter column createddate set default ('now'::text)::timestamp with time zone;
alter table usersorganizations alter column modifieddate set default ('now'::text)::timestamp with time zone;
alter table usertest alter column createddate set default ('now'::text)::timestamp with time zone;
alter table usertest alter column modifieddate set default ('now'::text)::timestamp with time zone;
