# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
echo I am provisioning...
date > /etc/vagrant_provisioned_at
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.synced_folder "C:\\vagrant\\scripts", "/scripts"
  config.vm.synced_folder "C:\\vagrant\\logs", "/logs"
  config.vm.synced_folder "C:\\vagrant\\pgdump", "/pgdump"
  config.vm.synced_folder "C:\\vagrant\\centos64-test\\Vagrant-setup", "/schema"
end

Vagrant::Config.run do |config|
  config.vm.box = "centos64"
  config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-vbox4210.box"
  ###config.vm.box_url = "https://github.com/tommy-muehle/puppet-vagrant-boxes/releases/download/1.0.0/centos-6.6-x86_64.box"
  config.vm.host_name = "localdev" 
  
  config.vm.share_folder "bootstrap", "/mnt/bootstrap", ".", :create => true
  config.vm.provision :shell, :path => "Vagrant-setup/bootstrap.sh"
  
  # PostgreSQL Server port forwarding
  config.vm.forward_port 5432, 15432
  
  # Apache Server port forwarding
  config.vm.forward_port 80, 8282
  
  # Postgrest Server port forwarding
  config.vm.forward_port 3000, 3001
  
end
